version: '2'
services:
  db:
    container_name: selia
    restart: unless-stopped
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'seliaApi'
    ports: 
      - 6612:3306
    volumes:
      - ./db_data:/var/lib/mysql

